import json
from pprint import pprint as pp

from datetime import datetime
from elasticsearch import Elasticsearch

from elasticsearch_learning.es_utils import *

es = Elasticsearch()
# pp(es.info())

# print(es.cat.indices(v=True))

# print(es.cat.aliases())
# res = es.indices.get_mapping(index=['news_20210624'])
pp(get_mapping(es, index=['rdnews']))
# {'news_20210624': {'mappings': {'dynamic_templates': [{'nohtml': {'mapping': {'enabled': False,
#                                                                               'type': 'object'},
#                                                                   'match': '*.html',
#                                                                   'match_mapping_type': 'string'}},
#                                                       {'noattach': {'mapping': {'enabled': False,
#                                                                                 'type': 'object'},
#                                                                     'match': '*.attachmenets',
#                                                                     'match_mapping_type': 'string'}}],
#                                 'properties': {'analyzer': {'properties': {'character': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                 'type': 'keyword'}},
#                                                                                          'type': 'text'},
#                                                                            'charactor': {'type': 'keyword'},
#                                                                            'country': {'type': 'keyword'},
#                                                                            'label': {'type': 'keyword'},
#                                                                            'label_raw': {'enabled': False,
#                                                                                          'type': 'object'},
#                                                                            'label_socre': {'enabled': False,
#                                                                                            'type': 'object'},
#                                                                            'recommend_score': {'enabled': False,
#                                                                                                'type': 'object'}}},
#                                                'crawler': {'properties': {'attachmenets': {'properties': {'generate_file_name': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                                         'type': 'keyword'}},
#                                                                                                                                  'type': 'text'},
#                                                                                                           'original_file_name': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                                         'type': 'keyword'}},
#                                                                                                                                  'type': 'text'},
#                                                                                                           'original_url': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                                   'type': 'keyword'}},
#                                                                                                                            'type': 'text'},
#                                                                                                           'position': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                               'type': 'keyword'}},
#                                                                                                                        'type': 'text'},
#                                                                                                           'relative_physical_path': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                                             'type': 'keyword'}},
#                                                                                                                                      'type': 'text'},
#                                                                                                           'relative_url_path': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                                        'type': 'keyword'}},
#                                                                                                                                 'type': 'text'},
#                                                                                                           'type': {'fields': {'keyword': {'ignore_above': 256,
#                                                                                                                                           'type': 'keyword'}},
#                                                                                                                    'type': 'text'}}},
#                                                                           'attachments': {'properties': {'generate_file_name': {'type': 'keyword'},
#                                                                                                          'original_file_name': {'enabled': False,
#                                                                                                                                 'type': 'object'},
#                                                                                                          'original_url': {'type': 'keyword'},
#                                                                                                          'position': {'enabled': False,
#                                                                                                                       'type': 'object'},
#                                                                                                          'relative_physical_path': {'enabled': False,
#                                                                                                                                     'type': 'object'},
#                                                                                                          'relative_url_path': {'enabled': False,
#                                                                                                                                'type': 'object'},
#                                                                                                          'type': {'type': 'keyword'}}},
#                                                                           'author': {'type': 'keyword'},
#                                                                           'column': {'type': 'keyword'},
#                                                                           'content': {'analyzer': 'ik_max_word',
#                                                                                       'search_analyzer': 'ik_smart',
#                                                                                       'type': 'text'},
#                                                                           'country_id': {'type': 'keyword'},
#                                                                           'date': {'type': 'date'},
#                                                                           'html': {'enabled': False,
#                                                                                    'type': 'object'},
#                                                                           'language': {'type': 'keyword'},
#                                                                           'shortDescription': {'analyzer': 'ik_max_word',
#                                                                                                'max_input_length': 50,
#                                                                                                'preserve_position_increments': True,
#                                                                                                'preserve_separators': True,
#                                                                                                'search_analyzer': 'ik_smart',
#                                                                                                'type': 'completion'},
#                                                                           'site': {'type': 'keyword'},
#                                                                           'summary': {'analyzer': 'ik_max_word',
#                                                                                       'max_input_length': 50,
#                                                                                       'preserve_position_increments': True,
#                                                                                       'preserve_separators': True,
#                                                                                       'search_analyzer': 'ik_smart',
#                                                                                       'type': 'completion'},
#                                                                           'title': {'analyzer': 'ik_max_word',
#                                                                                     'max_input_length': 50,
#                                                                                     'preserve_position_increments': True,
#                                                                                     'preserve_separators': True,
#                                                                                     'search_analyzer': 'ik_smart',
#                                                                                     'type': 'completion'},
#                                                                           'url': {'type': 'keyword'},
#                                                                           'website_id': {'type': 'keyword'}}},
#                                                'dev_favorites': {'type': 'long'},
#                                                'dev_like': {'type': 'long'},
#                                                'dev_view': {'type': 'long'},
#                                                'extract_character_state': {'type': 'long'},
#                                                'extract_charactor_state': {'type': 'long'},
#                                                'extract_country_state': {'type': 'long'},
#                                                'extract_label_state': {'type': 'long'},
#                                                'favorites': {'type': 'long'},
#                                                'fetch_state': {'type': 'long'},
#                                                'fetch_time': {'type': 'date'},
#                                                'id': {'type': 'keyword'},
#                                                'like': {'type': 'long'},
#                                                'prod_favorites': {'type': 'long'},
#                                                'prod_like': {'type': 'long'},
#                                                'prod_view': {'type': 'long'},
#                                                'recommend_state': {'type': 'long'},
#                                                'retrieval_state': {'type': 'long'},
#                                                'test': {'type': 'keyword'},
#                                                'translate_state': {'type': 'long'},
#                                                'translate_time': {'type': 'date'},
#                                                'translator': {'properties': {'en': {'properties': {'content': {'analyzer': 'ik_max_word',
#                                                                                                                'search_analyzer': 'ik_smart',
#                                                                                                                'type': 'text'},
#                                                                                                    'html': {'enabled': False,
#                                                                                                             'type': 'object'},
#                                                                                                    'summary': {'analyzer': 'ik_max_word',
#                                                                                                                'max_input_length': 50,
#                                                                                                                'preserve_position_increments': True,
#                                                                                                                'preserve_separators': True,
#                                                                                                                'search_analyzer': 'ik_smart',
#                                                                                                                'type': 'completion'},
#                                                                                                    'title': {'analyzer': 'ik_max_word',
#                                                                                                              'max_input_length': 50,
#                                                                                                              'preserve_position_increments': True,
#                                                                                                              'preserve_separators': True,
#                                                                                                              'search_analyzer': 'ik_smart',
#                                                                                                              'type': 'completion'}}},
#                                                                              'zh-CN': {'properties': {'content': {'analyzer': 'ik_max_word',
#                                                                                                                   'search_analyzer': 'ik_smart',
#                                                                                                                   'type': 'text'},
#                                                                                                       'html': {'enabled': False,
#                                                                                                                'type': 'object'},
#                                                                                                       'summary': {'analyzer': 'ik_max_word',
#                                                                                                                   'max_input_length': 50,
#                                                                                                                   'preserve_position_increments': True,
#                                                                                                                   'preserve_separators': True,
#                                                                                                                   'search_analyzer': 'ik_smart',
#                                                                                                                   'type': 'completion'},
#                                                                                                       'title': {'analyzer': 'ik_max_word',
#                                                                                                                 'max_input_length': 50,
#                                                                                                                 'preserve_position_increments': True,
#                                                                                                                 'preserve_separators': True,
#                                                                                                                 'search_analyzer': 'ik_smart',
#                                                                                                                 'type': 'completion'}}}}},
#                                                'view': {'type': 'long'}}}}}


pp(get_settings(es, index=['rdnews']))
# {'news_20210624': {'settings': {'index': {'creation_date': '1624518804921',
#                                           'max_result_window': '4890',
#                                           'number_of_replicas': '1',
#                                           'number_of_shards': '12',
#                                           'provided_name': 'news_20210624',
#                                           'refresh_interval': '1s',
#                                           'translog': {'durability': 'request',
#                                                        'sync_interval': '5s'},
#                                           'unassigned': {'node_left': {'delayed_timeout': '5m'}},
#                                           'uuid': 'lTj0KYliSZW9fPTg9wKnaA',
#                                           'version': {'created': '7050199'}}}}}


