version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - $HOME/data/mongors/mongo1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27021:27021
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip_all", "--port", "27021" ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - $HOME/data/mongors/mongo2:/data/db
    networks:
      - mongors-network
    ports:
      - 27022:27022
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip_all", "--port", "27022" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - $HOME/data/mongors/mongo3:/data/db
    networks:
      - mongors-network
    ports:
      - 27023:27023
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "dbrs", "--bind_ip_all", "--port", "27023" ]

networks:
  mongors-network:
    driver: bridge