version: '3.7'
services:
  nginx:
    image: nginx:1.22
    # container_name: my_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/etc/nginx/www
    ports:
      - "8080:80"
      - "8081:8000"
    depends_on:
      - web_1
      - web_2
      - web_3
      - web_4

  web_1:
    build: ./web
    # container_name: my_web_1
    expose:
      - 9999
    volumes:
      - ./web:/app
    environment:
      APPID: my_web_1
      TZ: Asia/Shanghai
  
  web_2:
    build: ./web
    container_name: my_web_2
    expose:
      - 9999
    volumes:
      - ./web:/app
    environment:
      APPID: my_web_2
      TZ: Asia/Shanghai
  
  web_3:
    build: ./web
    container_name: my_web_3
    expose:
      - 9999
    volumes:
      - ./web:/app
    environment:
      APPID: my_web_3
      TZ: Asia/Shanghai

  web_4:
    build: ./web
    container_name: my_web_4
    expose:
      - 9999
    volumes:
      - ./web:/app
    environment:
      APPID: my_web_4
      TZ: Asia/Shanghai
